# Generated by Django 5.0.7 on 2024-08-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_options_alter_status_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['pk'], 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
    ]
