# Generated by Django 5.0.7 on 2024-08-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_label_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
    ]
