# Generated by Django 5.0.7 on 2024-08-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
