# Generated by Django 5.0.7 on 2024-08-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_remove_label_tasks'),
        ('tasks', '0006_labeltaskconnection_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.LabelTaskConnection', to='labels.label'),
        ),
    ]
